# Generated by Django 3.0.8 on 2020-08-23 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_homelatestarrivals_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('stars', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('img1', models.FileField(blank=True, null=True, upload_to='')),
                ('img2', models.FileField(blank=True, null=True, upload_to='')),
                ('img3', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, choices=[('mens_shirt', 'mens_shirt'), ('mens_tshirt', 'mens_tshirt'), ('mens_jeans', 'mens_jeans'), ('mens_blazer', 'mens_blazer'), ('mens_kurta', 'mens_kurta'), ('womens_tops', 'womens_tops'), ('womens_dresses', 'womens_dresses'), ('womnes_jeans', 'womnes_jeans'), ('womens_saree', 'womens_saree'), ('womens_westernwear', 'womens_westernwear'), ('kids_boys', 'kids_boys'), ('kids_girls', 'kids_girls'), ('kids_infant', 'kids_infant')], default=1, max_length=30, null=True)),
                ('avail', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
