# Generated by Django 3.0.8 on 2020-08-23 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_homebestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebestseller',
            name='category',
            field=models.CharField(blank=True, choices=[('mens_shirt', 'mens_shirt'), ('mens_tshirt', 'mens_tshirt'), ('mens_jeans', 'mens_jeans'), ('mens_blazer', 'mens_blazer'), ('mens_kurta', 'mens_kurta'), ('womens_tops', 'womens_tops'), ('womens_dresses', 'womens_dresses'), ('womens_jeans', 'womens_jeans'), ('womens_saree', 'womens_saree'), ('womens_westernwear', 'womens_westernwear'), ('kids_boys', 'kids_boys'), ('kids_girls', 'kids_girls'), ('kids_infant', 'kids_infant')], default=1, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homebestseller',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homelatestarrivals',
            name='category',
            field=models.CharField(blank=True, choices=[('mens_shirt', 'mens_shirt'), ('mens_tshirt', 'mens_tshirt'), ('mens_jeans', 'mens_jeans'), ('mens_blazer', 'mens_blazer'), ('mens_kurta', 'mens_kurta'), ('womens_tops', 'womens_tops'), ('womens_dresses', 'womens_dresses'), ('womens_jeans', 'womens_jeans'), ('womens_saree', 'womens_saree'), ('womens_westernwear', 'womens_westernwear'), ('kids_boys', 'kids_boys'), ('kids_girls', 'kids_girls'), ('kids_infant', 'kids_infant')], default=1, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homelatestarrivals',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
