# Generated by Django 3.0.8 on 2020-08-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200823_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebestseller',
            old_name='id',
            new_name='uniqueid',
        ),
        migrations.RenameField(
            model_name='homelatestarrivals',
            old_name='id',
            new_name='uniqueid',
        ),
    ]
