# Generated by Django 3.0.8 on 2020-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200823_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebestseller',
            name='uniqueid',
        ),
        migrations.RemoveField(
            model_name='homelatestarrivals',
            name='uniqueid',
        ),
        migrations.AddField(
            model_name='homebestseller',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='homelatestarrivals',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
