# Generated by Django 3.0.8 on 2020-08-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200823_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBestSeller',
        ),
        migrations.DeleteModel(
            name='HomeLatestArrivals',
        ),
    ]
