# Generated by Django 3.0.8 on 2020-08-23 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0008_auto_20200823_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator])),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Image1', models.FileField(blank=True, null=True, upload_to='')),
                ('Image2', models.FileField(blank=True, null=True, upload_to='')),
                ('availability', models.BooleanField(blank=True, default=True, null=True)),
                ('latestArrival', models.BooleanField(blank=True, default=False, null=True)),
                ('bestSeller', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
