# Generated by Django 3.0.8 on 2020-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Mens-Shirt', 'Mens-Shirt'), ('Mens-Tshirt', 'Mens-Tshirt'), ('Mens-Jeans', 'Mens-Jeans'), ('Mens-Kurta', 'Mens-Kurta'), ('Mens-Blazer', 'Mens-Blazer'), ('Womens-Top', 'Womens-Top'), ('Womens-Dresses', 'Womens-Dresses'), ('Womens-Jeans', 'Womens-Jeans'), ('Womens-Saree', 'Womens-Saree'), ('Womens-Western wear', 'Womens-Western wear'), ('Kids-Boys', 'Kids-Boys'), ('Kids-Girls', 'Kids-Girls'), ('Kids-Infants', 'Kids-Infants')], default=1, max_length=30, null=True),
        ),
    ]
